#include <MKL25Z4.h> 
#include "constants.h"
#include "led.h"

void green_led_init() {
	PORTB->PCR[LED_GREEN_PIN] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[LED_GREEN_PIN] |= PORT_PCR_MUX(1);
	
	// Set pins to output
	PTB->PDDR |= MASK(LED_GREEN_PIN);
	
	// Turn off leds
	PTB->PDOR |= (MASK(LED_GREEN_PIN)); 
}

void green_led_running() {
	PTB->PTOR |= MASK(LED_GREEN_PIN);
}

void green_led_on() {
  PTB->PDOR &= ~MASK(LED_GREEN_PIN);
}

void red_led_init() {
	// Enable pins as gpio
	PORTC->PCR[LED_PTC1] &= ~PORT_PCR_MUX_MASK;
	PORTC->PCR[LED_PTC1] |= PORT_PCR_MUX(1);

	PORTC->PCR[LED_PTC2] &= ~PORT_PCR_MUX_MASK;
	PORTC->PCR[LED_PTC2] |= PORT_PCR_MUX(1);

	PORTE->PCR[LED_PTE30] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[LED_PTE30] |= PORT_PCR_MUX(1);
	
	PORTE->PCR[LED_PTE29] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[LED_PTE29] |= PORT_PCR_MUX(1);
	
	PORTB->PCR[LED_PTB3] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[LED_PTB3] |= PORT_PCR_MUX(1);
	
	PORTB->PCR[LED_PTB8] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[LED_PTB8] |= PORT_PCR_MUX(1);	

	PORTB->PCR[LED_PTB9] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[LED_PTB9] |= PORT_PCR_MUX(1);

	PORTB->PCR[LED_PTB10] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[LED_PTB10] |= PORT_PCR_MUX(1);
	
	PORTB->PCR[LED_PTB11] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[LED_PTB11] |= PORT_PCR_MUX(1);
	
	PORTE->PCR[LED_PTE2] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[LED_PTE2] |= PORT_PCR_MUX(1);
	
	// Set pins to output
	PTC->PDDR |= MASK(LED_PTC1);
	PTC->PDDR |= MASK(LED_PTC2);
	PTE->PDDR |= MASK(LED_PTE30);
	PTE->PDDR |= MASK(LED_PTE29);
	PTB->PDDR |= MASK(LED_PTB3);
	PTB->PDDR |= MASK(LED_PTB8);
	PTB->PDDR |= MASK(LED_PTB9);
	PTB->PDDR |= MASK(LED_PTB10);
	PTB->PDDR |= MASK(LED_PTB11);
	PTE->PDDR |= MASK(LED_PTE2);
	
	// Turn off leds
	PTC->PDOR |= MASK(LED_PTC1);
	PTC->PDOR |= MASK(LED_PTC2);
	PTE->PDOR |= MASK(LED_PTE30);
	PTE->PDOR |= MASK(LED_PTE29);
	PTB->PDOR |= MASK(LED_PTB3);
	PTB->PDOR |= MASK(LED_PTB8);
	PTB->PDOR |= MASK(LED_PTB9);
	PTB->PDOR |= MASK(LED_PTB10);
	PTB->PDOR |= MASK(LED_PTB11);
	PTE->PDOR |= MASK(LED_PTE2);	
}

void red_led_toggle() {
	PTC->PTOR |= MASK(LED_PTC1);
	PTC->PTOR |= MASK(LED_PTC2);
	PTE->PTOR |= MASK(LED_PTE30);
	PTE->PTOR |= MASK(LED_PTE29);
	PTB->PTOR |= MASK(LED_PTB3);
	PTB->PTOR |= MASK(LED_PTB8);
	PTB->PTOR |= MASK(LED_PTB9);
	PTB->PTOR |= MASK(LED_PTB10);
	PTB->PTOR |= MASK(LED_PTB11);
	PTE->PTOR |= MASK(LED_PTE2);	
}
